; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env]
framework = arduino
lib_deps = 
	esp32async/ESPAsyncWebServer @ ^3.7.10
	bblanchon/ArduinoJson @ ^6.21.5
	tzapu/WiFiManager @ ^2.0.17
	mickey9801/ButtonFever @ ^1.0
	ayushsharma82/ElegantOTA @ ^3.1.7
monitor_speed = 115200
build_flags = 
	-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-fexceptions

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = partitions-4MB.csv
monitor_filters = esp32_exception_decoder

[env:esp32dev-ota]
platform = espressif32
board = esp32dev
board_build.partitions = partitions-4MB.csv
monitor_filters = esp32_exception_decoder
extra_scripts = upload.py
upload_protocol = custom
custom_upload_url = http://192.168.178.155/update
custom_username = paper-boy
custom_password = thisisareallystrongpassword1234